package:
  name: ipyparallel_mesos
  version: 0.0.2

source:
  path: ../

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python
    - ipyparallel
    - ipython-notebook
    - requests

test:
  # Python imports
  imports:
    - ipyparallel_mesos

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ActivisionGameScience/ipyparallel-mesos
  license: BSD License
  summary: 'ipyparallel launchers for mesos using docker and marathon'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
